apiVersion: trainer.kubeflow.org/v1alpha1
kind: TrainJob
metadata:
  name: multikueue-hello-3
  namespace: default
  labels:
    kueue.x-k8s.io/queue-name: user-queue
spec:
  runtimeRef:
    apiGroup: trainer.kubeflow.org
    kind: ClusterTrainingRuntime
    name: torch-distributed
  trainer:
    image: busybox:1.36
    numNodes: 2
    command: ["/bin/sh", "-c"]
    args:
      - |
        echo "==== I am pod $HOSTNAME ===="
        echo "PET_NODE_RANK=$PET_NODE_RANK  PET_NNODES=$PET_NNODES"
        sleep 180
        echo "==== done ===="
    resourcesPerNode:
      requests:
        cpu: "1500m"
        memory: "512Mi"
      limits:
        cpu: "2"
        memory: "1Gi"